# Generated by Django 3.2.9 on 2021-11-09 12:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211109_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 12, 36, 34, 703685, tzinfo=utc)),
        ),
    ]
